### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/hasura-splicer

### ISSUE THREAD

**Issue by squk** [ferm10n/hasura-splicer#1]

**Comment by ferm10n** [comment]
This project is a work in progress, and I haven't published it yet. I should start on it again sometime soon.

I probably should have put a note on the readme to indicate the wip, my bad.

**Comment by squk** [comment]
Oh I see. Thanks. That's a bummer that the project isn't ready yet, I was super excited to use this. Managing metadata is a pain for me right now w/ Hasura's existing implementation. If this was a Go project, I'd be happy to contribute; unfortunately I have very little knowledge w/ typescript. 

Close this ticket at you discretion.

**Comment by ferm10n** [comment]
Ah man! I wish I knew Go more, I originally tried to see if I could edit the hasura-cli and moved to this because I thought it'd be easier than getting enough knowledge about how Go works in their project.

I actually had some thoughts about changing how users would interact with this tool. I'll probably make an issue describing these changes today or tomorrow. Would you mind if I tagged you to weigh in?

**Comment by squk** [comment]
Go for it!
